# Generated by Django 3.2.8 on 2021-12-22 04:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured_images', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('price', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project_priority_sl', models.IntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
