# Generated by Django 3.2.8 on 2021-12-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211224_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key_feature',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
