# Generated by Django 3.2.8 on 2021-12-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_key_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='key_feature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
