# Generated by Django 3.2.8 on 2021-12-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_key_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='basic_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='warranty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
