# Generated by Django 3.2.8 on 2022-04-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20211224_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('check_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
