# Generated by Django 3.2.8 on 2022-04-28 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20220423_1107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
